version: '3'
services:
  drgtracker:
    image: manayethas/drgtracker:dev  # You can replace with your local image if needed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db  # This maps the ./db folder on your local machine to /app/db inside the container
    environment:
      - FLASK_ENV=development  # Optional for dev purposes
    depends_on:
      - watchtower

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 0 * * *"  # Optional: Runs watchtower daily at midnight
