version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./db:/app/db
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: sqlite
    volumes:
      - ./db:/app/db
    command: sqlite3 /app/db/members_data.db
