name: Docker Image CI

on:
  push:
    branches:
      - main  # This means the workflow will run on push to the main branch.
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/your-repo-name:latest .
        docker push your-dockerhub-username/your-repo-name:latest

    - name: Log out from Docker Hub
      run: docker logout
